<?php

declare(strict_types=1);

namespace AqwSocketClient;

use AqwSocketClient\Interfaces\EventInterface;
use AqwSocketClient\Messages\{DelimitedMessage, JsonMessage, XmlMessage};
use Psr\Log\{LoggerInterface, NullLogger};
use React\Promise\{Deferred, PromiseInterface};
use React\Socket\{ConnectionInterface, Connector};
use RuntimeException;

/**
 * The main client class responsible for establishing and maintaining the
 * socket connection to the AQW server.
 *
 * It manages the I/O loop, processes incoming raw messages through interpreters,
 * and sends commands generated by translators back to the server.
 */
final class Client
{
    /**
     * @var ConnectionInterface|null The active socket connection instance, or null if disconnected.
     */
    private ?ConnectionInterface $connection = null;
    private string $buffer                   = '';

    /**
     * @param Server $server The configuration object describing the target AQW server (hostname, port, name).
     * @param Configuration $configuration The application configuration, including interpreters and translators.
     * @param LoggerInterface $logger A PSR-3 logger instance. Defaults to NullLogger if not provided.
     */
    public function __construct(
        private readonly Server $server,
        private readonly Configuration $configuration,
        private readonly LoggerInterface $logger = new NullLogger()
    ) {
    }

    /**
     * Attempts to establish an asynchronous TCP connection to the configured AQW server.
     *
     * This method initializes the connection, sets up handlers for data and connection
     * lifecycle events, and returns a promise that resolves upon successful connection
     * or rejects upon failure.
     *
     * @return PromiseInterface A promise that resolves upon successful connection or rejects upon failure.
     */
    public function connect(): PromiseInterface
    {
        $connector = new Connector();
        $deferred  = new Deferred();

        $target = "tcp://{$this->server->hostname}:{$this->server->port}";
        $this->logger->info("Attempting to connect to {$this->server->name} at {$target}.");

        $connector->connect($target)->then(
            function (ConnectionInterface $connection) use ($deferred): void {
                $this->logger->info("Connection to {$this->server->name} established.");

                $this->connection = $connection;
                $this->setupConnectionHandlers($connection);

                $deferred->resolve($connection);
            },
            function (\Throwable $e) use ($deferred): void {
                $this->logger->error("Failed to connect to {$this->server->name}: {$e->getMessage()}.");
                $deferred->reject($e);
            }
        );

        return $deferred->promise();
    }

    /**
     * Sets up event listeners for the established socket connection.
     *
     * Registers handlers for 'close' (connection termination) and 'data' (incoming server messages).
     *
     * @param ConnectionInterface $connection The active connection instance.
     */
    private function setupConnectionHandlers(ConnectionInterface $connection): void
    {
        $connection->on('close', function (): void {
            $this->logger->info("Connection to {$this->server->name} closed.");
            $this->connection = null;
            $this->buffer     = '';
        });

        $connection->on('data', function (string $data): void {
            $this->buffer .= $data;
            $this->processBuffer();
        });
    }

    /**
     * Processes the internal buffer, extracting and handling complete null-terminated messages.
     */
    private function processBuffer(): void
    {
        while (true) {
            $delimiterPosition = strpos($this->buffer, "\x00");

            if ($delimiterPosition === false) {
                break;
            }

            $rawMessage   = substr($this->buffer, 0, $delimiterPosition + 1);
            $this->buffer = substr($this->buffer, $delimiterPosition + 1);

            $this->processRawMessage($rawMessage);
        }
    }

    /**
     * Handles a single complete raw message extracted from the buffer.
     *
     * Parses the message, generates events via interpreters, dispatches them
     * to listeners, and sends back any resulting commands.
     *
     * @param string $rawMessage A complete null-terminated raw message string.
     */
    private function processRawMessage(string $rawMessage): void
    {
        $events = $this->parseEvents($rawMessage);

        $this->dispatchEvents($events);
        $this->sendCommands($events);
    }

    /**
     * Dispatches the given events to all registered listeners.
     *
     * @param EventInterface[] $events
     */
    private function dispatchEvents(array $events): void
    {
        foreach ($events as $event) {
            foreach ($this->configuration->listeners as $listener) {
                $listener->listen($event);
            }
        }
    }

    /**
     * Runs all given events through translators and sends any resulting commands.
     *
     * @param EventInterface[] $events
     */
    private function sendCommands(array $events): void
    {
        foreach ($events as $event) {
            foreach ($this->configuration->translators as $translator) {
                $command = $translator->translate($event);

                if ($command !== null) {
                    $this->sendPacket($command->pack());
                }
            }
        }
    }

    /**
     * Writes a pre-packaged {@see Packet} to the active socket connection.
     *
     * @param Packet $packet The packet ready to be sent.
     * @throws RuntimeException If called when the connection is not active.
     */
    private function sendPacket(Packet $packet): void
    {
        if ($this->connection === null) {
            throw new RuntimeException('Cannot send packet: connection is not open.');
        }

        $this->connection->write($packet->unpacketify());
    }

    /**
     * Sanitizes a raw message, parses it into all known message types,
     * and runs each through all configured interpreters to produce events.
     *
     * @param string $rawMessage The raw null-terminated string received from the socket.
     * @return EventInterface[] An array of events generated by all interpreters.
     */
    private function parseEvents(string $rawMessage): array
    {
        $sanitized = str_replace("\x00", '', $rawMessage);

        if ($this->configuration->logMessages) {
            $this->logger->debug($sanitized);
        }

        $messages = array_filter([
            XmlMessage::fromString($sanitized),
            DelimitedMessage::fromString($sanitized),
            JsonMessage::fromString($sanitized),
        ]);

        $events = [];
        foreach ($this->configuration->interpreters as $interpreter) {
            foreach ($messages as $message) {
                $events = array_merge($events, $interpreter->interpret($message));
            }
        }

        return $events;
    }
}
